/**
 * Type Definitions - {{PROJECT_NAME}}
 *
 * TODO: This file should be generated by Claude Code using the openai-app-builder skill.
 * Define Zod schemas for your API responses and tool inputs/outputs.
 */

import { z } from "zod";

// ============================================
// Example Schemas - Replace with actual types
// ============================================

export const ExampleItemSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string().optional(),
  imageUrl: z.string().url().optional(),
  createdAt: z.string().datetime().optional(),
});

export type ExampleItem = z.infer<typeof ExampleItemSchema>;

// ============================================
// Tool Input Schemas
// ============================================

export const SearchInputSchema = z.object({
  query: z.string().min(1, "Query is required"),
  limit: z.number().min(1).max(100).optional().default(10),
});

export type SearchInput = z.infer<typeof SearchInputSchema>;

// ============================================
// Tool Output Schemas
// ============================================

export const SearchResultSchema = z.object({
  items: z.array(ExampleItemSchema),
  totalCount: z.number(),
  query: z.string(),
});

export type SearchResult = z.infer<typeof SearchResultSchema>;
